### ISSUE TITLE
Error while executing xcodegen.sh

### ISSUE THREAD

**Issue by thbonk** [rhx/SwiftGtk#2]
I cloned the master branch and executing xcodegen.sh gives the following errors:

> Cloning into 'gir2swift'...
remote: Counting objects: 1242, done.
remote: Total 1242 (delta 0), reused 0 (delta 0), pack-reused 1242
Receiving objects: 100% (1242/1242), 189.36 KiB | 0 bytes/s, done.
Resolving deltas: 100% (837/837), done.
<unknown>:0: error: build had 1 command failures
error: exit(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/d021624/Projects/Private/macOS/SwiftGtk/.build/gir2swift/.build/debug.yaml
./gir-to-swift.sh: line 24: gir2swift: command not found
./gir-to-swift.sh: line 24: gir2swift: command not found
./gir-to-swift.sh: line 24: gir2swift: command not found
./gir-to-swift.sh: line 25: exec: gir2swift: not found
./gir-to-swift.sh: line 24: gir2swift: command not found
./gir-to-swift.sh: line 24: gir2swift: command not found
./gir-to-swift.sh: line 24: gir2swift: command not found
./gir-to-swift.sh: line 24: gir2swift: command not found
./gir-to-swift.sh: line 24: gir2swift: command not found
./gir-to-swift.sh: line 24: gir2swift: command not found
./xcodegen.sh: line 10: cd: Gtk.xcodeproj/Configs: No such file or directory

This is the entire output of the command:

> Cloning https://github.com/rhx/CGtk.git
HEAD is now at b8ef28f Add more gtk-3.22 types
Resolved version: 1.0.14
Cloning https://github.com/rhx/SwiftGdk.git
HEAD is now at 2068b0b Add support for gdk_gl_context_set_use_es()
Resolved version: 3.18.0
Cloning https://github.com/rhx/CGdk.git
HEAD is now at 0c0e9b1 Add more gdk-3.22 structs
Resolved version: 1.0.5
Cloning https://github.com/rhx/SwiftGdkPixbuf.git
HEAD is now at c2f6448 Add empty GdkPixbuf.swift to ensure git creates the 'Sources' directory
Resolved version: 2.46.0
Cloning https://github.com/rhx/CGdkPixbuf.git
HEAD is now at e8a9c3c Add #include <termios.h> so this compiles on Linux
Resolved version: 1.0.1
Cloning https://github.com/rhx/SwiftGIO.git
HEAD is now at fe6cfab Update for Swift-3.0 (release)
Resolved version: 2.46.0
Cloning https://github.com/rhx/SwiftGObject.git
HEAD is now at ddc8cec Add verbatim PARAM_READWRITE to make this compile on Ubuntu 14.04
Resolved version: 2.46.0
Cloning https://github.com/rhx/SwiftGLib.git
HEAD is now at a538f17 Add closure-friendly wrapper around g_timeout_add_full()
Resolved version: 2.46.0
Cloning https://github.com/rhx/CGLib.git
HEAD is now at fffb626 Add #include <termios.h> so this compiles on Linux
Resolved version: 1.0.14
Cloning https://github.com/rhx/SwiftGModule.git
HEAD is now at 60c8e9d Add empty GModule.swift to ensure git creates the 'Sources' directory
Resolved version: 2.46.0
Cloning https://github.com/rhx/SwiftPangoCairo.git
HEAD is now at 606dcb6 Add empty PangoCairo.swift to ensure git creates the 'Sources' directory
Resolved version: 2.46.0
Cloning https://github.com/rhx/SwiftCairo.git
HEAD is now at 5a074ff s/size/fontSize/
Resolved version: 2.46.0
Cloning https://github.com/rhx/CCairo.git
HEAD is now at bd6ba57 Fix cairo library name
Resolved version: 1.0.2
Cloning https://github.com/rhx/SwiftPango.git
HEAD is now at 3d1a569 Add empty Pango.swift to ensure git creates the 'Sources' directory
Resolved version: 2.46.0
Cloning https://github.com/rhx/CPango.git
HEAD is now at 803b906 Fix cairo library name
Resolved version: 1.0.2
Cloning https://github.com/rhx/SwiftAtk.git
HEAD is now at 5be8440 Add empty Atk.swift to ensure git creates the 'Sources' directory
Resolved version: 2.46.0
Cloning https://github.com/rhx/CAtk.git
HEAD is now at 694cbaa Add private structs so that public types get exported to Swift
Resolved version: 1.0.0
Cloning https://github.com/rhx/SwiftLibXML.git
HEAD is now at 1f41661 Update for Swift 3 preview 6
Resolved version: 1.2.0
Cloning https://github.com/rhx/CLibXML2.git
HEAD is now at 8b87520 Use CLibXML2 module name rather than libxml2
Resolved version: 1.0.1
Compile Swift Module 'SwiftLibXML' (6 sources)
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "libxml2_bridging.h"
        ^
/Users/d021624/Projects/Private/macOS/SwiftGtk/.build/gir2swift/Packages/CLibXML2-1.0.1/libxml2_bridging.h:12:9: note: in file included from /Users/d021624/Projects/Private/macOS/SwiftGtk/.build/gir2swift/Packages/CLibXML2-1.0.1/libxml2_bridging.h:12:
#import <libxml2/libxml/xmlreader.h>
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libxml2/libxml/xmlreader.h:13:10: error: 'libxml/xmlversion.h' file not found
#include <libxml/xmlversion.h>
         ^
/Users/d021624/Projects/Private/macOS/SwiftGtk/.build/gir2swift/Packages/SwiftLibXML-1.2.0/Sources/XMLAttribute.swift:14:8: error: could not build Objective-C module 'CLibXML2'
import CLibXML2
       ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "libxml2_bridging.h"
        ^
/Users/d021624/Projects/Private/macOS/SwiftGtk/.build/gir2swift/Packages/CLibXML2-1.0.1/libxml2_bridging.h:12:9: note: in file included from /Users/d021624/Projects/Private/macOS/SwiftGtk/.build/gir2swift/Packages/CLibXML2-1.0.1/libxml2_bridging.h:12:
#import <libxml2/libxml/xmlreader.h>
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libxml2/libxml/xmlreader.h:13:10: error: 'libxml/xmlversion.h' file not found
#include <libxml/xmlversion.h>
         ^
/Users/d021624/Projects/Private/macOS/SwiftGtk/.build/gir2swift/Packages/SwiftLibXML-1.2.0/Sources/XMLAttribute.swift:14:8: error: could not build Objective-C module 'CLibXML2'
import CLibXML2
       ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "libxml2_bridging.h"
        ^
/Users/d021624/Projects/Private/macOS/SwiftGtk/.build/gir2swift/Packages/CLibXML2-1.0.1/libxml2_bridging.h:12:9: note: in file included from /Users/d021624/Projects/Private/macOS/SwiftGtk/.build/gir2swift/Packages/CLibXML2-1.0.1/libxml2_bridging.h:12:
#import <libxml2/libxml/xmlreader.h>
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libxml2/libxml/xmlreader.h:13:10: error: 'libxml/xmlversion.h' file not found
#include <libxml/xmlversion.h>
         ^
/Users/d021624/Projects/Private/macOS/SwiftGtk/.build/gir2swift/Packages/SwiftLibXML-1.2.0/Sources/XMLAttribute.swift:14:8: error: could not build Objective-C module 'CLibXML2'
import CLibXML2
       ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "libxml2_bridging.h"
        ^
/Users/d021624/Projects/Private/macOS/SwiftGtk/.build/gir2swift/Packages/CLibXML2-1.0.1/libxml2_bridging.h:12:9: note: in file included from /Users/d021624/Projects/Private/macOS/SwiftGtk/.build/gir2swift/Packages/CLibXML2-1.0.1/libxml2_bridging.h:12:
#import <libxml2/libxml/xmlreader.h>
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libxml2/libxml/xmlreader.h:13:10: error: 'libxml/xmlversion.h' file not found
#include <libxml/xmlversion.h>
         ^
/Users/d021624/Projects/Private/macOS/SwiftGtk/.build/gir2swift/Packages/SwiftLibXML-1.2.0/Sources/XMLAttribute.swift:14:8: error: could not build Objective-C module 'CLibXML2'
import CLibXML2
       ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "libxml2_bridging.h"
        ^
/Users/d021624/Projects/Private/macOS/SwiftGtk/.build/gir2swift/Packages/CLibXML2-1.0.1/libxml2_bridging.h:12:9: note: in file included from /Users/d021624/Projects/Private/macOS/SwiftGtk/.build/gir2swift/Packages/CLibXML2-1.0.1/libxml2_bridging.h:12:
#import <libxml2/libxml/xmlreader.h>
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libxml2/libxml/xmlreader.h:13:10: error: 'libxml/xmlversion.h' file not found
#include <libxml/xmlversion.h>
         ^
/Users/d021624/Projects/Private/macOS/SwiftGtk/.build/gir2swift/Packages/SwiftLibXML-1.2.0/Sources/XMLAttribute.swift:14:8: error: could not build Objective-C module 'CLibXML2'
import CLibXML2
       ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "libxml2_bridging.h"
        ^
/Users/d021624/Projects/Private/macOS/SwiftGtk/.build/gir2swift/Packages/CLibXML2-1.0.1/libxml2_bridging.h:12:9: note: in file included from /Users/d021624/Projects/Private/macOS/SwiftGtk/.build/gir2swift/Packages/CLibXML2-1.0.1/libxml2_bridging.h:12:
#import <libxml2/libxml/xmlreader.h>
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libxml2/libxml/xmlreader.h:13:10: error: 'libxml/xmlversion.h' file not found
#include <libxml/xmlversion.h>
         ^
/Users/d021624/Projects/Private/macOS/SwiftGtk/.build/gir2swift/Packages/SwiftLibXML-1.2.0/Sources/XMLAttribute.swift:14:8: error: could not build Objective-C module 'CLibXML2'
import CLibXML2
       ^
Generate Swift Wrapper for Atk-2.46.0
Generate Swift Wrapper for Cairo-2.46.0
Generate Swift Wrapper for GIO-2.46.0
Generate Swift Wrapper for GLib-2.46.0
Generate Swift Wrapper for GModule-2.46.0
Generate Swift Wrapper for GObject-2.46.0
Generate Swift Wrapper for Gdk-3.18.0
Generate Swift Wrapper for GdkPixbuf-2.46.0
Generate Swift Wrapper for Pango-2.46.0
Generate Swift Wrapper for PangoCairo-2.46.0
generated: ./Gtk.xcodeproj

**Comment by rhx** [comment]
The structure of the Xcode projects generated by the Swift Package Manager has changed.  This caused the scripts to fail.  The latest version now works with Xcode 8.3.1 (Swift 3.1)
