### ISSUE TITLE
Unable to finish compile on Ubuntu 18.04 LTS with Swift 5.1

### ISSUE THREAD

**Issue by ksubryan** [rhx/SwiftGtk#13]
Failed to reconstruct type for $sSo13__va_list_tagVmD
Original type:
(metatype_type
  (struct_type decl=__ObjC.(file).__va_list_tag))
Stack dump:
0.	Program arguments: /usr/share/swift/usr/bin/swift -frontend -c /home/kri

**Comment by rhx** [comment]
Yes, this seems to be a bug in the 5.1 prerelease on Linux (as of 5.1-DEVELOPMENT-SNAPSHOT-2019-08-12-a).  It works fine for me under Swift 5.0.2 (as well as 5.1 under macOS).

**Comment by ksubryan** [comment]
Actually it is something else.
I resolved all issues regarding Swift 5.1 use on Linux in VSCode. I can build and debug all my projects.
To test I installed 5.0.2 on Ubuntu 18.04 and results were the same.
SwiftGTK compiles without issues until it reaches GTKHelpers. 
In my case, reconstruction failure results from inability of the compiler to located <gtk/gtk.h>. (it is in the usual location and is found by other projects).
The first error crops up for 
.build/checkouts/SwiftGTK/Sources/GTKHelpers/gtk_dialog.c
when preprocessors is unable to located #include <gtk/gtk.h> in gtk_dialog.h.
"missing" file is located in /usr/include
inspecting flags passed compiler revels -Xcc -I/usr/include/gtk-3.0

Exact same behaviour with Swift 5.0.2 & 5.1. 

Also it would be nice to understand why warnings happen around
" Generate Swift Wrapper for SwiftPango
warning: you may be able to install glib-2.0 gio-unix-2.0 using your system-packager: "

**Comment by msenol86** [comment]
> Actually it is something else.
> I resolved all issues regarding Swift 5.1 use on Linux in VSCode. I can build and debug all my projects.
> To test I installed 5.0.2 on Ubuntu 18.04 and results were the same.
> SwiftGTK compiles without issues until it reaches GTKHelpers.
> In my case, reconstruction failure results from inability of the compiler to located <gtk/gtk.h>. (it is in the usual location and is found by other projects).
> The first error crops up for
> .build/checkouts/SwiftGTK/Sources/GTKHelpers/gtk_dialog.c
> when preprocessors is unable to located #include <gtk/gtk.h> in gtk_dialog.h.
> "missing" file is located in /usr/include
> inspecting flags passed compiler revels -Xcc -I/usr/include/gtk-3.0
> 
> Exact same behaviour with Swift 5.0.2 & 5.1.
> 
> Also it would be nice to understand why warnings happen around
> " Generate Swift Wrapper for SwiftPango
> warning: you may be able to install glib-2.0 gio-unix-2.0 using your system-packager: "

I have the same issue. How can I fix that?

**Comment by rhx** [comment]
Can you try running

bash -x ./build.sh

and post the output?

**Comment by msenol86** [comment]
> Can you try running
> 
> ```
> ./distclean.sh
> bash -x ./build.sh
> ```
> 
> and post the output?
> 
> [Edit: added distclean]

I have also restored config.sh to original form.


[swiftgtk.log](https://github.com/rhx/SwiftGtk/files/3694972/swiftgtk.log)

**Comment by ksubryan** [comment]
I have seen this issue with VSCode with C. I could not find it now but I 
saww some comments on this issue in VSCode issues.

Mucahit, would you be kind and post your configuration for VSCode? I had 
hard time making it to work.


Rene,

My latest attempt to build with swift 5.1 post from October 4th produced 
this error.

/home/kristof/Development/SwiftProjects/Swift+GTK/SwiftHelloGtk-master/.build/checkouts/SwiftGLib/Sources/GLib/GLib.swift:22:23: 
error: use of unresolved identifier 'getVaList'
         let va_list = getVaList(varargs)

It is repeated many items and eventually results in a crash for swift.

To the best of my knowledge, Apple identified issue with the crash but 
the internal bug is not assigned and no work was done to address the 
issue. The crash is attributed to an assert in the compiler and "owner" 
of the assert is identified as well.


Attempt to build on OSX with 5.0.1 compiled correctly with no issues, 
other than warning about need to change protocol for hashable but when 
attempt to run produced core dump. I have not had time to look into 
fixing as I more interested in Ubuntu version.

**Comment by rhx** [comment]
Yes, this is a bit unfortunate.  I have committed a workaround that fixes the `getVaList()` compilation problem for GLib now, but compiling SwiftGtk under Linux (with either 5.0.3 or 5.1) still yields
`Failed to reconstruct type for $sSo13__va_list_tagVmD`

**Comment by rhx** [comment]
@msenol86: This should be working again under Linux using Swift 4.2.4 (you need to `git pull` and `./distclean.sh` to ensure the latest versions are downloaded).

**Comment by msenol86** [comment]
@rhx Thanks it compiled on 4.2.4 . Thank you very much.

**Comment by smumryak** [comment]
Hey @rhx 
i'm hitting the same issue on swift 5.1.3
```
$ swift --version
Swift version 5.1.3 (swift-5.1.3-RELEASE)
Target: x86_64-unknown-linux-gnu
```
Any chance you could point me to the direction of the issue you were looking back in October?

**Comment by rhx** [comment]
I have investigated some more, and it appears the bug only occurs when va_lists are created from within glib functions.  Can you do a `./distclean.sh` and check if this compiles with 5.1.3 for you now?

**Comment by smumryak** [comment]
Thanks @rhx, now compiler does not crash because of `va_lists`. Tho i've been trying to build 'SwiftHelloGTK' right now and it fails with
```
Gio-2.0-callbacks.swift:166:45: error: use of undeclared type 'GDesktopAppLaunchCallback'
public typealias DesktopAppLaunchCallback = GDesktopAppLaunchCallback
```
But I guess this is completely different topic.

**Comment by rhx** [comment]
Which version of glib do you have installed?

**Comment by rhx** [comment]
Okay, I have pushed a workaround for versions of glib that no longer define `GDesktopAppLaunchCallback` but still have it in their `.gir` files.  Can you pull, do another `./distclean.sh`, and see if this works for you now?
