### ISSUE TITLE
Not compiling with Swift 5.3

### ISSUE THREAD

**Issue by lschmierer** [rhx/SwiftGtk#27]
The library is not compiling with Swift 5.3 (bundled with Xcode 12 Beta).

```
/... /.build/checkouts/SwiftGLib/Sources/GLib/GLib-2.0-OptionContext.swift:434:58: error: ambiguous use of 'cast'
            g_option_context_set_description(cast(_ptr), cast(newValue))
                                                         ^
```

**Comment by rhx** [comment]
Code generated with gir2swift-11 now compiles with Swift 5.3.
